### ISSUE TITLE
Standardized and scalable Unity-based VR training creation tool.

### ISSUE THREAD

**Issue by Gusinuhe** [proyecto26/awesome-unity#1]
Hola 👋!

En mi compañía [Innoactive](https://www.innoactive.io/) acabamos de liberar el código de nuestra herramienta hecha en Unity que permite desarrollar entrenamientos en VR en una forma rápida, estándar y muy escalable.

Sería genial poder agregar [The Creator](https://github.com/Innoactive/Creator) a la lista 👍

**Comment by jdnichollsc** [comment]
Claro que si! Envía por favor el pull request para agregarla! 👍
